//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid CombatAI = new Guid("f8a030bf-c75b-4a67-b6ee-a23c5a946e58");
		public static readonly Guid CombatAI_002 = new Guid("f04816e1-a3ff-45d8-8307-273d8191c352");
		public static readonly Guid CommunicateMemory = new Guid("dd1d24e8-5d79-494b-8893-6a8600ddd369");
		public static readonly Guid CustomUtilityAI = new Guid("ab8a81bb-ca2f-44fc-ab17-04b2c030ad06");
		public static readonly Guid EntityScanner = new Guid("c3095717-47fb-44ae-9044-f0cc746951fc");
		public static readonly Guid ExampleAI = new Guid("8d53e04b-f6c0-4067-9848-9dd89f28a49a");
		public static readonly Guid MemoryCleanupAI = new Guid("675eaaa8-d26a-47a4-911d-3b8cfe329dad");
		public static readonly Guid PositionScannerAI = new Guid("4fd984cf-0221-4e35-84ea-b5ac08b9d766");
		public static readonly Guid PositionScorerAI = new Guid("94d5d5f1-a4c7-4a6b-8e47-11094e0eb248");
		public static readonly Guid ScannerTutorialAI = new Guid("6f88943e-ae7f-44da-8c72-2d9ef3809120");
		public static readonly Guid SerializationExample = new Guid("9ac850fa-506b-48d1-ab20-100218883ff5");
		public static readonly Guid TargetSelectionTutorialAI = new Guid("e7d1d3c3-7795-46fd-93f1-d954482ebbce");
		public static readonly Guid test = new Guid("a03cf3dc-532c-404d-8937-47d559cc6002");

    }
}
